name: ${project.name}
description: ${project.description}
main: ${project.main}
version: ${project.version}
api-version: ${project.api.version}
authors:
  - XodiumSoftware
database: false
load: ${project.load}
commands:
  vanillaplus:
    description: Main command for VanillaPlus
    permission: vanillaplus.gui
    usage: /vanillaplus
    aliases: [vp]
permissions:
  vanillaplus.doublevanilla:
    description: Allows to open double vanilla with one click
    default: true
  vanillaplus.reload:
    description: Allows to reload the config using /vanillaplus
    default: op
  vanillaplus.knock:
    description: Allows to knock on vanilla using left-click
    default: true
  vanillaplus.ironvanilla:
    description: Allows to open iron vanilla using right-click
    default: op
  vanillaplus.autoclose:
    description: Allows players to have their vanilla close automatically
    default: true
